# Generated by Django 6.0.2 on 2026-05-03 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_payment_link_payment_session_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="price_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID цены Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="product_id",
            field=models.CharField(
                blank=True, max_length=255, null=True, verbose_name="ID продукта Stripe"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[
                    ("created", "Создан"),
                    ("paid", "Оплачен"),
                    ("unpaid", "Не оплачен"),
                    ("canceled", "Отменен"),
                ],
                default="created",
                max_length=20,
                verbose_name="Статус платежа",
            ),
        ),
    ]
